name: Checks

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Install Tensorflow
        run: bun pm trust --all
      - name: Test
        run: bun run test
